version: 2
jobs:
  test:
    docker:
      - image: 891714082543.dkr.ecr.us-west-2.amazonaws.com/rackspace-tf-toolbox
    working_directory: ~/
    steps:
      - attach_workspace:
          at: ~/workspace
      - checkout:
            path: ~/branches/${CIRCLE_BRANCH}
      - run:
          name: Pre-test setup tasks
          command: |
            cp -vpr ~/branches/${CIRCLE_BRANCH}/.circleci/bin/* ~/bin/
            pip install -U pip tox tox-pyenv boto3
      - run:
          name: lint python code
          command: |
            cd ~/branches/${CIRCLE_BRANCH}
            tox
      - run:
          name: Run Test
          command: MODULE_CI_JOB='test' python3 orchestrate.py
      - run:
          name: apply ASG updates
          command: cd ~ && ~/bin/apply_update.sh
      - run:
          name: destroy
          command: cd ~ && ~/bin/destroy.sh && ~/bin/destroy_s3_buckets.sh # must succeed or we have something to clean up manually
          when: always
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - plan_results/*
            - artifacts/*
  check_destruction:
    docker:
      - image: 891714082543.dkr.ecr.us-west-2.amazonaws.com/rackspace-tf-toolbox
    working_directory: ~/
    steps:
      - attach_workspace:
          at: ~/workspace
      - checkout:
            path: ~/module
      - run:
          name: Check Destruction
          command: MODULE_CI_JOB='check_destruction' python3 orchestrate.py
      - store_artifacts:
          path: ~/workspace/artifacts


workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            branches:
             ignore: master
      - check_destruction:
          requires:
            - test
          filters:
            branches:
             ignore: master
